lib/cosmo_web/router.ex
defmodule CosmoWeb.Router do
  use CosmoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CosmoWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/cities/query", CityController, :query
    get "/cities/random", CityController, :random
    get "/properties/query", PropertyController, :query
    get "/properties/random", PropertyController, :random

    resources "/cities", CityController
    resources "/properties", PropertyController
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug, schema: Cosmo.Graphql
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL,
    schema: Cosmo.Graphql,
    context: %{pubsub: Cosmo.Endpoint}
end

lib/cosmo_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>
  <%= gettext "Welcome to %{name}!", name: "Cosmo" %>
  </h1>
  <p>
    A demo project to explore
    <a href="https://elixir-lang.org/">#ElixirLang</a>'s
    <a href="https://hexdocs.pm/phoenix/overview.html">Phoenix</a> /
    <a href="https://hexdocs.pm/ecto/Ecto.html">Ecto</a> /
    <a href="https://hexdocs.pm/absinthe/overview.html">Absinthe</a>
    using a couple of separate, unrelated datasets:
    <span><%= link "Cities", to: Routes.city_path(@conn, :index) %></span>
    and
    <span><%= link "Properties", to: Routes.property_path(@conn, :index) %></span>
  </p>
  <br/>
  <p>
    See also:<br/>––</br>
    <ul>
      <li><a href="./api">/api</a> for GraphQL endpoint</li>
      <li><a href="./graphiql">/graphiql</a> for GraphiQL interface</li>
      <li><a href="./help">/help</a> for all endpoints available</li>
    </ul>
  </p>
</section>